services:
  backend:
    image: karim129/smol-url
    ports:
      - "8001:80"
    env_file:
      - .env
    depends_on:
      - redis-cache
  redis-cache:
    image: redis
    ports:
      - "6379:6379"